version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/application
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
    - location: start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: build
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root